---
title: "Academic Work"
format: html
editor: visual
---

[Home](https://jennaahart.github.io/ahartwebsite/Index.html)

## Journalism Theory and Practice Midterm

This month, Jackie Wattles and Kristin Fisher wrote a piece for CNN entitled \"NASA tracks a newly discovered asteroid that has a 'small chance' of hitting Earth in 2046.\" The article summarizes NASA\'s research on asteroid 2023 DW, which has been predicted to come near Earth in February 2046. Still, the chance of impact is less than one in 500, and the article clarifies that the threat is relatively negligible.[\[1\]](#_ftn1)

This article abides well by Walter Lippmann\'s principles. Particularly, it focuses on expert opinion, taking a bird\'s eye view of the topic at hand. In his *Public Opinion*, Lippmann describes that the ideal form of information is sourced from an \"independent, expert organization for making the unseen facts intelligible.\"[\[2\]](#_ftn2)

In Wattles and Fisher\'s article, the piece mainly relies on relaying expert research. The quoted sources include engineers from NASA\'s Jet Propulsion Laboratory, Center of Near Object Studies, and Asteroid Watch Campaign. These sources all clearly demonstrate expert credibility and research---as Lippmann\'s ideology would warrant.

There is also an emphasis on factual, objective information, with the article discussing how the asteroid \"ranks 1 out of 10 on the Torino Impact Hazard Scale, a metric for categorizing the projected risk of an object colliding with Earth,\"[\[3\]](#_ftn3) and \"has a 1 in 625 chance of striking Earth, based on data projections from the European Space Agency.\"[\[4\]](#_ftn4) Again, this tactic reveals otherwise hidden facts to the public.

The authors\' approach to the article also mitigates public speculation. Throughout the piece, there is a clear focus on addressing a concern for collision. The writers clarify that the chances of collision are small and can be combatted by changing the trajectory of the asteroid.[\[5\]](#_ftn5) Similarly, Lippmann discusses how objective, expertly sourced reporting is necessary to combat the \"kind of portraiture which arises spontaneously in people's minds.\"[\[6\]](#_ftn6) Effectively, by presenting the objective facts of the circumstances, the authors of this article abide by Lippmann\'s principles, replacing individual speculation with a third-party, expert perspective.

Still, the article could have been made even more impactful by employing Dewey\'s principles. Dewey argues that effective reporting must take into account the communities it impacts, which, in this circumstance is the global citizenry. Dewey specifically mentions that \"No government by experts in which the masses do not have the chance to inform the experts as to their needs can be anything but an oligarchy managed in the interests of the few.\"[\[7\]](#_ftn7)

This article may not necessitate technical information from the masses, but it certainly could be aided by seeking out public opinion. The writers could have sought out concerns from the public, asking citizens whether they think the asteroid will hit Earth, whether the potential collision scares them, or what they would like to know about the asteroid.

The authors could have achieved this goal of answering public curiosity even without directly asking individuals. By taking to Twitter or other social platforms, the writers could find the public\'s most pressing questions and concerns about the asteroid in order to better guide their writing.

To further alleviate public concern, the writers could answer these questions in the articles. A potential format might include a quote about an individual\'s question or worry, followed by the response of an expert in the field.

By directly addressing the perspective of the masses in this article, the authors would make a more compelling piece that abides by Dewey\'s emphasis on involving impacted communities. Readers would better relate to the piece, seeing their own questions directly answered by subject matter experts. Simultaneously, the article would address mass speculation in a way that directly involves the communities it intends to aid.

For this topic, a citizen journalist approach to reporting would be difficult to navigate. Because the available information is largely available only to field experts and researchers, the involvement of citizens in news writing is less realistic.

Still, an overall understanding of the impacts of the asteroid\'s impact could be aided by a community-based approach. Especially if the asteroid were to become a true threat through potential collision, citizen-based reporting would develop a more thorough understanding of the public\'s reaction to the event.

In Alissa Richardson\'s study of citizen reporting during the Black Lives Matter movement, she found that the public was able to aid coverage through candid, readily accessible depictions of crucial political events, saying, \"The activists who participated in this study embodied this spirit of dogged determination. With their smartphones in hand, they were armed with a new kind of weapon.\"[\[8\]](#_ftn8)

In the hypothetical situation that the asteroid becomes a real danger, as Richardson depicts above, citizen journalists could aid coverage by providing photos and videos of public reactions. This could include rioting, stocking up at stores, or any other resulting chaos. In this way, the global citizenry would better document the state of the world around them as news develops on the state of the asteroid.

# Works Cited

Lippmann, Walter. *Public Opinion*. 1st Free Press pbks. ed. New York: Free Press Paperbacks, 1997.

Richardson, Allissa V. Bearing Witness While Black : African Americans, Smartphones, and the New Protest #Journalism. New York, NY: Oxford University Press, 2020.

Rogers, Melvin L. \"Introduction: Revisiting The Public and Its Problems.\" Contemporary pragmatism 7, no. 1 (2010): 1--7.

Wattles, Jackie, and Kristin Fisher. \"NASA Tracks a Newly Discovered Asteroid That Has a 'Small Chance' of Hitting Earth in 2046.\" CNN. Cable News Network, March 10, 2023. https://www.cnn.com.

[\[1\]](#_ftnref1) Wattles & Fisher, \"NASA tracks newly discovered asteroid\"

[\[2\]](#_ftnref2) Lippmann, *Public Opinion*, 31

[\[3\]](#_ftnref3) Wattles & Fisher, \"NASA tracks newly discovered asteroid\"

[\[4\]](#_ftnref4) Abid

[\[5\]](#_ftnref5)Abid

[\[6\]](#_ftnref6) Lippmann, *Public Opinion*, 8

[\[7\]](#_ftnref7) Rogers, \"Revisiting the Public,\" 26-27

[\[8\]](#_ftnref8) Richardson, *Bearing Witness*, 398This month, Jackie Wattles and Kristin Fisher wrote a piece for CNN entitled \"NASA tracks a newly discovered asteroid that has a 'small chance' of hitting Earth in 2046.\" The article summarizes NASA\'s research on asteroid 2023 DW, which has been predicted to come near Earth in February 2046. Still, the chance of impact is less than one in 500, and the article clarifies that the threat is relatively negligible.[\[1\]](#_ftn1)

# 
